"""Release delta report (`DELTA_LOG.md`): what a runtime release changed in
the web and device lanes, observed from outside.

Diffs the two most recent sweep snapshots per model x backend — and, since
Phase 13, the two most recent device-run snapshots per runtime per
model x device x accelerator: status regressions and improvements (the
DECISIONS #62 status vocabulary via `browser_status` / `device_status` — one
status derivation per lane, no second dialect), metric shifts beyond a
configured threshold, catalog changes, and transform rules currently flagged
stale (spec 11.4). Entries are generated only, deterministic, and upserted by
heading — never hand-edited.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from litert_compat.cards.index import browser_status
from litert_compat.device_runs.records import DeviceRunSnapshot, device_status, record_label
from litert_compat.freshness.snapshots import SweepSnapshot
from litert_compat.matrix.canonical import load_json

#: Lower is better; identical to the site's STATUS_RANK order.
STATUS_RANK = {
    "pass": 0,
    "fallback": 1,
    "output_mismatch": 2,
    "run_failed": 3,
    "load_failed": 4,
}

DELTA_LOG_HEADER = """# DELTA_LOG — observed per-release changes (web + device lanes)

Generated by `edge-compat freshness delta` (Phase 11; device lane added in
Phase 13) — never hand-edited. Each entry diffs the two most recent sweep
snapshots under `data/sweep/`, or the two most recent device-run snapshots of
one runtime under `data/device_runs/` (model-level facts only; op-level
matrix entries are never derived from either — the trap rule, both editions).
The native-matrix counterpart is the Phase 8 `release-check` report.
"""


def _statuses(snapshot: SweepSnapshot) -> dict[tuple[str, str], dict[str, Any]]:
    """(model_id, backend) -> the backend record, for every record present."""
    records: dict[tuple[str, str], dict[str, Any]] = {}
    for model_id, doc in snapshot.models.items():
        for record in doc.get("results", []):
            records[(model_id, record["backend"])] = record
    return records


def collect_stale_rules(rules_dir: Path | None) -> list[dict[str, Any]]:
    """Rules currently flagged `stale` in a rules directory, sorted by id.
    Read leniently (id + stale block only): the delta report lists staleness,
    it does not re-validate the rules lane."""
    if rules_dir is None or not rules_dir.is_dir():
        return []
    stale: list[dict[str, Any]] = []
    for path in sorted(rules_dir.glob("*.json")):
        try:
            doc = load_json(path)
        except (OSError, ValueError):
            continue
        if isinstance(doc, dict) and isinstance(doc.get("stale"), dict):
            block = doc["stale"]
            stale.append(
                {
                    "id": str(doc.get("id", path.stem)),
                    "date": str(block.get("date", "")),
                    "runtime": str(block.get("runtime", "")),
                    "runtime_version": str(block.get("runtime_version", "")),
                    "reason": str(block.get("reason", "")),
                }
            )
    return sorted(stale, key=lambda r: r["id"])


def compute_delta(
    old: SweepSnapshot,
    new: SweepSnapshot,
    *,
    latency_threshold_pct: float,
    stale_rules: list[dict[str, Any]],
) -> dict[str, Any]:
    """Deterministic delta document between two snapshots."""
    old_records = _statuses(old)
    new_records = _statuses(new)

    regressions: list[dict[str, Any]] = []
    improvements: list[dict[str, Any]] = []
    latency_shifts: list[dict[str, Any]] = []
    for key in sorted(old_records.keys() & new_records.keys()):
        model_id, backend = key
        old_status = browser_status(old_records[key])
        new_status = browser_status(new_records[key])
        if old_status != new_status:
            change = {
                "model_id": model_id,
                "backend": backend,
                "old_status": old_status,
                "new_status": new_status,
                "failure_class": new_records[key].get("failure_class"),
            }
            if STATUS_RANK[new_status] > STATUS_RANK[old_status]:
                regressions.append(change)
            else:
                improvements.append(change)
        old_ms = old_records[key].get("latency_p50_ms")
        new_ms = new_records[key].get("latency_p50_ms")
        if old_ms and new_ms is not None:
            change_pct = round((new_ms - old_ms) / old_ms * 100, 1)
            if abs(change_pct) > latency_threshold_pct:
                latency_shifts.append(
                    {
                        "model_id": model_id,
                        "backend": backend,
                        "old_ms": old_ms,
                        "new_ms": new_ms,
                        "change_pct": change_pct,
                    }
                )

    delta: dict[str, Any] = {
        "old": {"litertjs_version": old.litertjs_version, "date": old.date},
        "new": {"litertjs_version": new.litertjs_version, "date": new.date},
        "latency_threshold_pct": latency_threshold_pct,
        "regressions": regressions,
        "improvements": improvements,
        "latency_shifts": latency_shifts,
        "models_added": sorted(new.models.keys() - old.models.keys()),
        "models_removed": sorted(old.models.keys() - new.models.keys()),
        "records_added": sorted(
            f"{m} x {b}" for m, b in new_records.keys() - old_records.keys() if m in old.models
        ),
        "records_removed": sorted(
            f"{m} x {b}" for m, b in old_records.keys() - new_records.keys() if m in new.models
        ),
        "stale_rules": stale_rules,
    }
    delta["has_changes"] = any(
        delta[key]
        for key in (
            "regressions",
            "improvements",
            "latency_shifts",
            "models_added",
            "models_removed",
            "records_added",
            "records_removed",
            "stale_rules",
        )
    )
    return delta


def entry_heading(delta: dict[str, Any]) -> str:
    old, new = delta["old"], delta["new"]
    return (
        f"## @litertjs/core {old['litertjs_version']} → {new['litertjs_version']} "
        f"(sweep {old['date']} → {new['date']})"
    )


def _device_records(snapshot: DeviceRunSnapshot) -> dict[tuple[str, str, str], dict[str, Any]]:
    """(model_id, device, record label) -> the accelerator record. The label
    carries the prompt-length condition ('gpu@205tok'), so two conditions of
    one accelerator are two records, and a condition change between snapshots
    reads as record added/removed — never as a fake metric shift."""
    records: dict[tuple[str, str, str], dict[str, Any]] = {}
    for (model_id, device), doc in snapshot.docs.items():
        for record in doc.get("results", []):
            records[(model_id, device, record_label(record))] = record
    return records


#: Numeric fields the device delta watches for shifts. Direction is reported
#: signed; the reader judges — a faster decode and a slower latency both show.
_DEVICE_METRICS = ("latency_p50_ms", "decode_tokens_per_s", "prefill_tokens_per_s")


def compute_device_delta(
    old: DeviceRunSnapshot,
    new: DeviceRunSnapshot,
    *,
    metric_threshold_pct: float,
) -> dict[str, Any]:
    """Deterministic delta between two device-run snapshots of one runtime."""
    old_records = _device_records(old)
    new_records = _device_records(new)

    regressions: list[dict[str, Any]] = []
    improvements: list[dict[str, Any]] = []
    metric_shifts: list[dict[str, Any]] = []
    for key in sorted(old_records.keys() & new_records.keys()):
        model_id, device, accelerator = key
        old_status = device_status(old_records[key])
        new_status = device_status(new_records[key])
        if old_status != new_status:
            change = {
                "model_id": model_id,
                "device": device,
                "accelerator": accelerator,
                "old_status": old_status,
                "new_status": new_status,
                "failure_class": new_records[key].get("failure_class"),
            }
            if STATUS_RANK[new_status] > STATUS_RANK[old_status]:
                regressions.append(change)
            else:
                improvements.append(change)
        for metric in _DEVICE_METRICS:
            old_value = old_records[key].get(metric)
            new_value = new_records[key].get(metric)
            if old_value and new_value is not None:
                change_pct = round((new_value - old_value) / old_value * 100, 1)
                if abs(change_pct) > metric_threshold_pct:
                    metric_shifts.append(
                        {
                            "model_id": model_id,
                            "device": device,
                            "accelerator": accelerator,
                            "metric": metric,
                            "old": old_value,
                            "new": new_value,
                            "change_pct": change_pct,
                        }
                    )

    old_files = set(old.docs.keys())
    new_files = set(new.docs.keys())
    delta: dict[str, Any] = {
        "runtime": new.runtime,
        "old": {"runtime_version": old.runtime_version, "date": old.date},
        "new": {"runtime_version": new.runtime_version, "date": new.date},
        "metric_threshold_pct": metric_threshold_pct,
        "regressions": regressions,
        "improvements": improvements,
        "metric_shifts": metric_shifts,
        "models_added": sorted(f"{m} on {d}" for m, d in new_files - old_files),
        "models_removed": sorted(f"{m} on {d}" for m, d in old_files - new_files),
        "records_added": sorted(
            f"{m} on {d} x {a}"
            for m, d, a in new_records.keys() - old_records.keys()
            if (m, d) in old_files
        ),
        "records_removed": sorted(
            f"{m} on {d} x {a}"
            for m, d, a in old_records.keys() - new_records.keys()
            if (m, d) in new_files
        ),
    }
    delta["has_changes"] = any(
        delta[key]
        for key in (
            "regressions",
            "improvements",
            "metric_shifts",
            "models_added",
            "models_removed",
            "records_added",
            "records_removed",
        )
    )
    return delta


def device_entry_heading(delta: dict[str, Any]) -> str:
    old, new = delta["old"], delta["new"]
    return (
        f"## {delta['runtime']} {old['runtime_version']} → {new['runtime_version']} "
        f"(device runs {old['date']} → {new['date']})"
    )


def render_device_entry(delta: dict[str, Any]) -> str:
    """Markdown entry for one runtime's device-run delta, deterministic."""
    lines = [device_entry_heading(delta), ""]

    def section(title: str, rows: list[str]) -> None:
        if rows:
            lines.append(f"### {title} ({len(rows)})")
            lines.extend(rows)
            lines.append("")

    def status_row(c: dict[str, Any]) -> str:
        row = (
            f"- `{c['model_id']}` on `{c['device']}` x `{c['accelerator']}`: "
            f"{c['old_status']} → **{c['new_status']}**"
        )
        if c["failure_class"]:
            row += f" (failure class: `{c['failure_class']}`)"
        return row

    section("Regressions", [status_row(c) for c in delta["regressions"]])
    section(
        "Improvements",
        [status_row({**c, "failure_class": None}) for c in delta["improvements"]],
    )
    section(
        f"Metric shifts (>{delta['metric_threshold_pct']:g}% |Δ|)",
        [
            f"- `{c['model_id']}` on `{c['device']}` x `{c['accelerator']}` "
            f"{c['metric']}: {c['old']:g} → {c['new']:g} "
            f"({'+' if c['change_pct'] >= 0 else ''}{c['change_pct']:g}%)"
            for c in delta["metric_shifts"]
        ],
    )
    catalog = [f"- added: `{m}`" for m in delta["models_added"]]
    catalog += [f"- removed: `{m}`" for m in delta["models_removed"]]
    catalog += [f"- record added: `{r}`" for r in delta["records_added"]]
    catalog += [f"- record removed: `{r}`" for r in delta["records_removed"]]
    section("Catalog changes", catalog)
    if not delta["has_changes"]:
        lines.append("No observed changes.")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_entry(delta: dict[str, Any]) -> str:
    """Markdown entry for DELTA_LOG.md, deterministic."""
    lines = [entry_heading(delta), ""]

    def section(title: str, rows: list[str]) -> None:
        if rows:
            lines.append(f"### {title} ({len(rows)})")
            lines.extend(rows)
            lines.append("")

    section(
        "Regressions",
        [
            f"- `{c['model_id']}` x `{c['backend']}`: {c['old_status']} → **{c['new_status']}**"
            + (f" (failure class: `{c['failure_class']}`)" if c["failure_class"] else "")
            for c in delta["regressions"]
        ],
    )
    section(
        "Improvements",
        [
            f"- `{c['model_id']}` x `{c['backend']}`: {c['old_status']} → **{c['new_status']}**"
            for c in delta["improvements"]
        ],
    )
    section(
        f"Latency shifts (>{delta['latency_threshold_pct']:g}% |Δ| p50)",
        [
            f"- `{c['model_id']}` x `{c['backend']}`: {c['old_ms']:g} ms → {c['new_ms']:g} ms "
            f"({'+' if c['change_pct'] >= 0 else ''}{c['change_pct']:g}%)"
            for c in delta["latency_shifts"]
        ],
    )
    catalog = [f"- added: `{m}`" for m in delta["models_added"]]
    catalog += [f"- removed: `{m}`" for m in delta["models_removed"]]
    catalog += [f"- backend added: `{r}`" for r in delta["records_added"]]
    catalog += [f"- backend removed: `{r}`" for r in delta["records_removed"]]
    section("Catalog changes", catalog)
    section(
        "Transform rules flagged stale",
        [
            f"- `{r['id']}`: {r['reason']} (flagged {r['date']}, {r['runtime']} "
            f"{r['runtime_version']})"
            for r in delta["stale_rules"]
        ],
    )
    if not delta["has_changes"]:
        lines.append("No observed changes.")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def upsert_entry(log_path: Path, delta: dict[str, Any]) -> bool:
    """Write the entry into DELTA_LOG.md: replace the block with the same
    heading if present (idempotent), append otherwise. Returns True when the
    file's bytes changed. Sweep deltas and device-run deltas (which carry a
    `runtime` key) render to their own entry shapes."""
    if "runtime" in delta:
        entry = render_device_entry(delta)
        heading = device_entry_heading(delta)
    else:
        entry = render_entry(delta)
        heading = entry_heading(delta)
    original = log_path.read_text(encoding="utf-8") if log_path.is_file() else DELTA_LOG_HEADER

    lines = original.splitlines(keepends=True)
    start = next((i for i, line in enumerate(lines) if line.rstrip("\n") == heading), None)
    if start is None:
        updated = original.rstrip("\n") + "\n\n" + entry
    else:
        end = next(
            (i for i in range(start + 1, len(lines)) if lines[i].startswith("## ")), len(lines)
        )
        updated = "".join(lines[:start]) + entry + "\n" + "".join(lines[end:])
        updated = updated.rstrip("\n") + "\n"
    if updated != original or not log_path.is_file():
        log_path.write_text(updated, encoding="utf-8")
        return updated != original
    return False
